### ISSUE TITLE
[BUG]House in sleeping mode linked to hotbox too

### ISSUE THREAD

**Issue by FUNKDATSHhhhhh** [maxi1134/Home-Assistant-Config#38]
When you pur the house on sleeping mode the hotbox goes on sleeping mode too and my lights start dimming too.

**Comment by maxi1134** [comment]
This is caused by https://github.com/basnijholt/adaptive-lighting; A ticket has been placed within their repo at https://github.com/basnijholt/adaptive-lighting/issues/737

I can try to mitigate this issue in the meantime by implementing a better detection for the "all sleeping" sensor at 
on line  https://github.com/maxi1134/Home-Assistant-Config/blob/d905da7c340cc68b111cb110442471a6017b756c/includes/template.yaml#L7

It seems to be only checking if I am sleeping instead of doing a check of all users.

**Comment by maxi1134** [comment]
Creating a few sensors to get a better "all sleeping" sensor 
fb808fbe761620a3b8bf8de6681b25191ade697a
ba6c7b45a3422d0f25e7e9eb991e8dabbbecd920

**Comment by maxi1134** [comment]
Seems fixed
